### ISSUE TITLE
build all room list interface

### ISSUE THREAD

**Issue by CyrusCai** [JavaScriptAcademy/Whisper-Client#6]
- [x] build interface template  for all rooms #7 
- [x] wrap room info as a individual template #8 
- [x] add 'New Room ' button at the bottom of this page #9
